 command = "npm run build"
  publish = "dist"

  [build.rollup]
    external = [
      "@mui/material/styles/index.js",
      "@mui/material/utils/index.js",
      "@mui/material/Alert/index.js"

    ]

[[redirects]]
  from = "/*"
  to = "/index.html"
